# Generated by Django 4.1.3 on 2022-11-28 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0004_alter_club_meeting_time"),
    ]

    operations = [
        migrations.CreateModel(
            name="Leardership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=20)),
                ("designation", models.CharField(blank=True, max_length=50)),
                ("date_created", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
