# Generated by Django 4.1.3 on 2022-11-28 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0005_leardership"),
    ]

    operations = [
        migrations.RenameModel(old_name="Leardership", new_name="Leadership",),
    ]
