# Generated by Django 4.1.3 on 2022-11-28 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0006_rename_leardership_leadership"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leadership",
            name="name",
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
