# Generated by Django 4.1.3 on 2022-11-28 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0007_alter_leadership_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="leadership",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="leadership/"),
        ),
    ]
